import React, { useState } from 'react';

const reportTypes = [
  { id: 'monthly', name: 'Monthly Payroll Register', icon: '📋' },
  { id: 'department', name: 'Department Wise Payroll', icon: '🏢' },
  { id: 'bonus', name: 'Bonus Report', icon: '💰' },
  { id: 'pf', name: 'Provident Fund Report', icon: '🏦' },
  { id: 'loan', name: 'Loan Report', icon: '📝' },
  { id: 'tax', name: 'Tax Deduction Report', icon: '📊' },
  { id: 'overtime', name: 'Overtime Report', icon: '⏰' },
  { id: 'bank', name: 'Bank Transfer Report', icon: '🏧' },
];

const recentReports = [
  { id: 1, name: 'January 2026 Payroll Register', type: 'monthly', generatedAt: '2026-02-05 10:30 AM', generatedBy: 'Admin' },
  { id: 2, name: 'December 2025 Bank Transfer', type: 'bank', generatedAt: '2026-01-05 11:15 AM', generatedBy: 'Admin' },
  { id: 3, name: 'Q4 2025 Bonus Report', type: 'bonus', generatedAt: '2026-01-03 09:00 AM', generatedBy: 'Admin' },
  { id: 4, name: 'FY 2025 PF Statement', type: 'pf', generatedAt: '2026-01-01 08:00 AM', generatedBy: 'Admin' },
];

const PayrollReports: React.FC = () => {
  const [selectedReport, setSelectedReport] = useState<string | null>(null);
  const [filterMonth, setFilterMonth] = useState('January 2026');
  const [showGenerateModal, setShowGenerateModal] = useState(false);

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Payroll Reports</h1>
          <p className="text-gray-500">Generate and view payroll reports</p>
        </div>
      </div>

      {/* Report Types */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {reportTypes.map((report) => (
          <button
            key={report.id}
            onClick={() => {
              setSelectedReport(report.id);
              setShowGenerateModal(true);
            }}
            className="p-6 bg-white rounded-xl border border-gray-100 hover:border-blue-300 hover:shadow-sm transition-all text-center"
          >
            <div className="text-4xl mb-2">{report.icon}</div>
            <p className="text-sm font-medium text-gray-900">{report.name}</p>
          </button>
        ))}
      </div>

      {/* Recent Reports */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="p-4 border-b border-gray-100">
          <h3 className="font-semibold text-gray-900">Recent Reports</h3>
        </div>
        <table className="w-full">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Report Name</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Type</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Generated At</th>
              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Generated By</th>
              <th className="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {recentReports.map((report) => (
              <tr key={report.id} className="hover:bg-gray-50">
                <td className="px-6 py-4 font-medium text-gray-900">{report.name}</td>
                <td className="px-6 py-4">
                  <span className="px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded">
                    {report.type}
                  </span>
                </td>
                <td className="px-6 py-4 text-gray-600">{report.generatedAt}</td>
                <td className="px-6 py-4 text-gray-600">{report.generatedBy}</td>
                <td className="px-6 py-4 text-center">
                  <button className="text-blue-600 hover:text-blue-800 mr-2">View</button>
                  <button className="text-green-600 hover:text-green-800">Download</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Generate Report Modal */}
      {showGenerateModal && selectedReport && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-lg">
            <div className="p-6 border-b border-gray-100">
              <h2 className="text-xl font-bold text-gray-900">
                Generate {reportTypes.find(r => r.id === selectedReport)?.name}
              </h2>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Select Month</label>
                <select
                  value={filterMonth}
                  onChange={(e) => setFilterMonth(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg"
                >
                  <option value="January 2026">January 2026</option>
                  <option value="December 2025">December 2025</option>
                  <option value="November 2025">November 2025</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Department (Optional)</label>
                <select className="w-full px-4 py-2 border border-gray-300 rounded-lg">
                  <option value="">All Departments</option>
                  <option value="academic">Academic</option>
                  <option value="admin">Administration</option>
                  <option value="it">IT</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Export Format</label>
                <div className="flex gap-4">
                  <label className="flex items-center gap-2">
                    <input type="checkbox" defaultChecked className="rounded border-gray-300" />
                    <span>PDF</span>
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" defaultChecked className="rounded border-gray-300" />
                    <span>Excel</span>
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" className="rounded border-gray-300" />
                    <span>CSV</span>
                  </label>
                </div>
              </div>
            </div>
            <div className="p-6 border-t border-gray-100 flex justify-end gap-3">
              <button
                onClick={() => setShowGenerateModal(false)}
                className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50"
              >
                Cancel
              </button>
              <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
                Generate Report
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default PayrollReports;
